# Generated by Django 4.1.5 on 2023-02-05 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_image')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('date_birth', models.DateField()),
                ('sex', models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина'), ('Другое', 'Другое')], default='Другое', max_length=100)),
                ('material_status', models.CharField(choices=[('Женат/Замужем', 'Женат/Замужем'), ('Одинок(а)', 'Одинок(а)'), ('Вдовец/Вдова', 'Вдовец/Вдова'), ('Разведён(а)', 'Разведён(а)')], default='Одинок(а)', max_length=100)),
                ('addressLine1', models.CharField(max_length=200, null=True)),
                ('addressLine2', models.CharField(max_length=200, null=True)),
                ('suburb', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('phoneNumber', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField()),
                ('cover_letter', models.FileField(upload_to='resumes')),
                ('cv', models.FileField(upload_to='resumes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, null=True)),
                ('position', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('experience', models.TextField()),
                ('skills', models.TextField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, null=True)),
                ('qualification', models.CharField(max_length=200, null=True)),
                ('level', models.CharField(choices=[('Среднее образование', 'Среднее образование'), ('Среднее профессиональное образование', 'Среднее профессиональное образование'), ('Бакалавриат высшего образования', 'Бакалавриат высшего образования'), ('Специалитет высшего образования', 'Специалитет высшего образования'), ('Магистратура высшего образования', 'Магистратура высшего образования'), ('Аспирантура', 'Аспирантура'), ('Докторская степень', 'Докторская степень')], default='Среднее образование', max_length=200)),
                ('start_date', models.DateField()),
                ('graduated', models.DateField()),
                ('major_subject', models.CharField(max_length=200, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.resume')),
            ],
        ),
    ]
