# Generated by Django 4.1.5 on 2023-02-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Образования'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Опыт работы', 'verbose_name_plural': 'Опыты работы'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
    ]
