# Generated by Django 4.1.5 on 2023-02-14 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_education_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='major_subject',
            new_name='direction',
        ),
    ]
