# Generated by Django 4.1.5 on 2023-02-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_major_subject_education_direction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='direction',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='qualification',
            new_name='specialization',
        ),
    ]
