# Generated by Django 4.1.5 on 2023-04-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_resume_suburb'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
