# Generated by Django 4.1.5 on 2023-04-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_resume_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=573487),
            preserve_default=False,
        ),
    ]
