# Generated by Django 4.1.5 on 2023-04-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_resume_image_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
