# Generated by Django 4.1.5 on 2023-04-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_uniqueid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='cover_letter',
        ),
    ]
