# Generated by Django 4.1.5 on 2023-04-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
