# Generated by Django 4.1.5 on 2023-02-01 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('FT', 'Полная'), ('PT', 'Неполная'), ('RT', 'Удаленная')], default='FT', max_length=10)),
                ('experience', models.CharField(choices=[('t1', 'Меньше 2 лет'), ('t2', 'от 2 до 5 лет'), ('t3', 'от 5 до 10 лет'), ('t4', 'от 10 до 15 лет'), ('t5', 'Больше 15 лет')], default='t1', max_length=10)),
                ('summary', models.TimeField()),
                ('description', models.TimeField()),
                ('logo', models.ImageField(default='default.png', upload_to='upload_images')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
