# Generated by Django 4.1.5 on 2023-02-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobs_options_alter_jobs_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='logo',
            field=models.ImageField(blank=True, upload_to='company_logo'),
        ),
    ]
