# Generated by Django 4.1.5 on 2023-03-01 18:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobs_experience_alter_jobs_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('categoryImage', models.ImageField(default='category.png', upload_to='category-image')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('seoDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('seoKeywords', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('companyLogo', models.ImageField(default='default.png', upload_to='company_logo')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('seoDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('seoKeywords', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='logo',
        ),
        migrations.AddField(
            model_name='jobs',
            name='applications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='closingDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobs',
            name='datePosted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='duties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='enquiries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='seoDescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='seoKeywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='urlLink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='experience',
            field=models.CharField(choices=[('Меньше 2 лет', 'Меньше 2 лет'), ('2-5 лет', 'от 2 до 5 лет'), ('5-10 лет', 'от 5 до 10 лет'), ('10-15 лет', 'от 10 до 15 лет'), ('>15 лет', 'Больше 15 лет')], default='Меньше 2 лет', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='type',
            field=models.CharField(choices=[('Полный', 'Полная'), ('Неполный', 'Неполная'), ('Удаленно', 'Удаленно')], default='Полный', max_length=100),
        ),
        migrations.AddField(
            model_name='jobs',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.category'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.company'),
        ),
    ]
