# Generated by Django 4.1.5 on 2023-03-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_category_company_remove_jobs_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='enquiries',
        ),
    ]
