# Generated by Django 4.1.5 on 2023-03-31 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_jobs_enquiries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='location',
            new_name='city',
        ),
    ]
