# Generated by Django 4.1.5 on 2023-04-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_jobs_applications_alter_jobs_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='filled',
            field=models.BooleanField(default=False),
        ),
    ]
