# Generated by Django 4.1.5 on 2023-04-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_applicant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name': 'Заявитель', 'verbose_name_plural': 'Заявители'},
        ),
    ]
