# Generated by Django 4.1.5 on 2023-04-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_applicant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryImage',
            field=models.ImageField(default='category.jpg', upload_to='category-image'),
        ),
    ]
