# Generated by Django 4.1.5 on 2023-04-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_remove_jobs_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyLogo',
            field=models.ImageField(default='company.png', upload_to='company_logo'),
        ),
    ]
