# Generated by Django 4.1.5 on 2023-04-20 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_alter_company_companylogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='addressLine',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='inn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='company',
            name='ogrn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(1000000000000), django.core.validators.MaxValueValidator(9999999999999)], verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='company',
            name='ogrnip',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(100000000000000), django.core.validators.MaxValueValidator(999999999999999)], verbose_name='ОГРНИП'),
        ),
        migrations.AddField(
            model_name='company',
            name='url',
            field=models.URLField(blank=True, max_length=128, null=True, unique=True, verbose_name='Ссылка на сайт'),
        ),
    ]
