# Generated by Django 4.1.5 on 2023-06-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='message',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_file',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_text',
            field=models.TextField(blank=True),
        ),
    ]
