# Generated by Django 4.1.5 on 2023-04-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatroom_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
    ]
