# Generated by Django 4.1.5 on 2023-04-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
