# Generated by Django 4.1.5 on 2023-06-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_blog', '0006_comment_delete_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post.jpg', upload_to='company_blog'),
        ),
    ]
